#! /bin/sh

sxhkd &
compton &
bspc monitor -d I II III IV V VI VII VIII IX X
# mouse focus
bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color \#930A65
bspc config normal_border_color \#026198

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-scale ~/wallpapers/dan-gold-344761.jpg
polybar top
